services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/netnax/docker_apps/iot/homeassistant/data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 3g
          cpus: '2.5'    # limit container to 2.5 CPUs (out of 8)
