networks:
  iot:
    external: true

services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable-rk
    shm_size: "128mb" # update for your cameras based on calculation above
    #devices:
    #  - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/netnax/docker_apps/iot/frigate/config:/config
      - /home/netnax/docker_apps/iot/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    #ports:
      #- "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      #- "8554:8554" # RTSP feeds
      #- "1984:1984" # go2rtc web interface
      #- "8555:8555/tcp" # WebRTC over tcp
      #- "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    networks:
        iot:
            ipv4_address: 172.28.0.3
